disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - nesting
  - function_parameter_count
  - trailing_whitespace
  - force_try
  - function_body_length
  - force_cast
  - superfluous_disable_command
  - line_length
  - comment_spacing
  - statement_position
  - opening_brace
  - implicit_getter
  - multiple_closures_with_trailing_closure
  - vertical_whitespace

opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
included: # paths to include during linting. `--path` is ignored if present.
  - Capstone Project
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# force_cast: warning # implicitly. Give warning only for force casting

# force_try:
#   severity: warning # explicitly. Give warning only for force try

type_body_length:
  - 300 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
  - 3
  - 4

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 55
  allowed_symbols: "_" # enable the use of underscore
  excluded: iPhone # excluded via string

# line_length:
#   warning: 250
#   ignores_comments: true

identifier_name:
  allowed_symbols: "_"

reporter: "xcode"
